### ISSUE TITLE
Документация по v0.2

### ISSUE THREAD

**Issue by lumian** [lumian/grcentral#27]
В текущей документации необходимы следующие изменения:
- [x] Добавить информацию о новом разделе системных настроек ( Issue #16 и #28 )
- [x] Добавить информацию о новом разделе "Справочник" ( Issue #3 )
- [x] Добавить информацию про настройку номера голосовой почты ( Issue #23 )
- [x] Добавить подробное описание конфигурационных настроек в группах моделей устройств: что такое, где искать, как заполнять ( Issue #26 )
- [x] Добавить информацию по чтению логов устройств ( Issue #8 )

**Comment by lumian** [comment]
Документация актуализирована под версию GRCentral 0.2.

**Comment by lumian** [comment]
Документация по логам устройств добавлена.

**Закрыто.**
